# permissions for end users to edit dshells.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dshell-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller-dshell
    app.kubernetes.io/part-of: controller-dshell
    app.kubernetes.io/managed-by: kustomize
  name: dshell-editor-role
rules:
- apiGroups:
  - dshell.smartx.com
  resources:
  - dshells
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dshell.smartx.com
  resources:
  - dshells/status
  verbs:
  - get
